services:
  app:
    image: thecodingmachine/php:8.2-v4-cli
    environment:
      PHP_EXTENSIONS: gd intl
      PHP_INI_MAX_EXECUTION_TIME: 240
      PHP_INI_MAX_INPUT_VARS: 1500
      PHP_INI_MEMORY_LIMIT: 256M
    volumes:
      - .:/usr/src/app